name: wdt_panglaodb
channels:
  - anaconda
  - salilab
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - appdirs=1.4.3
  - astroid=2.4.2
  - attrs=20.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - black=19.10b0
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - click=7.1.2
  - cycler=0.10.0
  - decorator=4.4.2
  - freetype=2.10.2
  - iniconfig=1.0.1
  - ipykernel=5.3.4
  - ipython=7.18.1
  - isort=5.4.2
  - jedi=0.17.2
  - joblib=0.16.0
  - jpeg=9d
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgomp=9.3.0
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - lz4-c=1.9.2
  - matplotlib-base=3.3.1
  - mccabe=0.6.1
  - more-itertools=8.5.0
  - ncurses=6.2
  - nltk=3.5
  - numpy=1.19.1
  - olefile=0.46
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.1.1
  - parso=0.7.1
  - pathspec=0.8.0
  - patsy=0.5.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pluggy=0.13.1
  - prompt-toolkit=3.0.7
  - ptyprocess=0.6.0
  - py=1.9.0
  - pygments=2.6.1
  - pylint=2.6.0
  - pyparsing=2.4.7
  - pytest=6.0.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.1
  - pyzmq=19.0.2
  - readline=8.0
  - regex=2020.7.14
  - rope=0.17.0
  - scipy=1.5.2
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.12.0
  - tabulate=0.8.7
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.0.4
  - tqdm=4.48.2
  - typed-ast=1.4.1
  - wcwidth=0.2.5
  - wheel=0.35.1
  - wrapt=1.11.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - antlr4-python3-runtime==4.8
    - backoff==1.10.0
    - beautifulsoup4==4.9.1
    - cfgraph==0.2.1
    - chardet==3.0.4
    - flask==1.1.2
    - flask-cors==3.0.9
    - future==0.18.2
    - idna==2.10
    - ipython-genutils==0.2.0
    - isodate==0.6.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jsonasobj==1.2.1
    - livereload==2.6.3
    - lunr==0.5.8
    - markdown==3.2.2
    - markupsafe==1.1.1
    - mkdocs==1.1.2
    - mkdocs-material==5.5.12
    - mkdocs-material-extensions==1.0
    - mkdocstrings==0.13.0
    - mwoauth==0.3.7
    - oauthlib==3.1.0
    - pbr==5.5.0
    - pyjsg==0.10.0
    - pyjwt==1.7.1
    - pymdown-extensions==8.0
    - pyshex==0.7.14
    - pyshexc==0.8.2
    - pytkdocs==0.7.0
    - pyyaml==5.3.1
    - rdflib==5.0.0
    - rdflib-jsonld==0.5.0
    - reconciler==0.1.3
    - requests==2.24.0
    - requests-oauthlib==1.3.0
    - seaborn==0.11.0
    - shexer==0.0.8
    - shexjsg==0.7.0
    - simplejson==3.17.2
    - soupsieve==2.0.1
    - sparql-slurper==0.3.4
    - sparqlwrapper==1.8.5
    - traitlets==5.0.4
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - wikidata-panglaodb==0.1.0
    - wikidata2df==0.1.0
    - wikidataintegrator==0.7.4
