# https://w.wiki/ep3
SELECT ?item ?itemLabel ?kind ?kindLabel
WHERE 
{
  ?item wdt:P279* wd:Q7868.
  OPTIONAL{?item wdt:P31 ?kind.}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}