# This workflow will automatically deploy the mkdocs documentation
# while installing the necessary Python dependencies.
# See https://parkererickson.github.io/portfolio/blog/MkDocsCD/

name: docs

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install mkdocs-material
          pip install mkdocstrings
          
      - name: Install NLTK corpora
        run: |
          python -m nltk.downloader punkt
          
      - name: Deploy
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          mkdocs gh-deploy
